alias vscode="code"
alias vs-code="code"
alias cdiff="code -d"
alias cadd="code -a"
alias cnew="code -n"
alias code-install="code --install-extension"
alias code-uninstall="code --uninstall-extension"
